### PR TITLE
:zap: improve build performance with vendors libs built once

### PR DESCRIPTION
**Pull request by bpetetot**
#4

### CODE REVIEW

**Review by fabienjuif — CHANGES_REQUESTED** [review]
We have to do this for DEV purpose only.
In a production purpose, we need to use webpack treeshaking, avoiding big js files.

Can you add a test on the NODE_ENV environment variable so we don't load vendors files in production ? Or an other workaround.

**Review by fabienjuif — APPROVED** [review]

**Comment by fabienjuif** [comment]
LGTM

**Comment by bpetetot** [comment]
1. **In production :** use webpack treeshaking
2. **In development :** use prebuilt vendors libs (with `npm run vendors`)
2. `vendors` folder created : it contains vendor libs for dev
3. `npm run build` created

I've still got one :shit:, with the index.html... it always contains vendors `<script>` calls in production build

**Comment by fabienjuif** [comment]
Yeah I ask myself about this.
But for a first iteration this is very well done 👍

**Pull request merged**
