### PR TITLE
:hammer: #43 / New way to synchronize clients/server

### PR DESCRIPTION
**Pull request by fabienjuif**

### CODE REVIEW

**Review by bpetetot — APPROVED** [review]
better and smoother than the old way 👍 
but can we manage balls synchro in the same way ? because balls moves will not be trigerred by players...

**Comment by fabienjuif** [comment]
I believe the ball will be like a client, but on the server side.
So this is "same" way of thinking.

**Comment by bpetetot** [comment]
ok you can merge 👍

**Comment by fabienjuif** [comment]
I'd like to fix circleCI on an other branch first

**Pull request merged**
